---

- name: Creating developer 1 "{{ developer1 }}" without admin rights
  user: name={{ developer1 }} password={{ dev_pass1 | password_hash('sha512') }} shell=/bin/bash generate_ssh_key=yes ssh_key_bits=2048

- name: Creating developer 2 "{{ developer2 }}" without admin rights
  user: name={{ developer2 }} password={{ dev_pass2 | password_hash('sha512') }} shell=/bin/bash generate_ssh_key=yes ssh_key_bits=2048 

- name: Creating developer 2 "{{ developer3 }}" without admin rights
  user: name={{ developer3 }} password={{ dev_pass3 | password_hash('sha512') }} shell=/bin/bash generate_ssh_key=yes ssh_key_bits=2048 

- name: Creating account for app1 "{{ testapp1 }}"
  user: name={{ testapp1 }} 

- name: Creating account for app2 "{{ testapp2 }}"
  user: name={{ testapp2 }} 

- name: Creating account for app3 "{{ testapp3 }}"
  user: name={{ testapp3 }} 

#- name: install apt packages
#  apt: "name='{{ item }}' state=present"
#  with_items:
#    - git
#    - python-pip

#- name: Install docker-py
#  pip: 
#      name=docker-py 
#      state=present
#      version=1.1.0

#- include: docker-jenkins.yml

- include: firejail.yml
- include: jenkins.yml
- include: gerrit.yml
- include: transmission.yml
