---
# Installation
- name: Install Transmission
  apt:
    name: transmission-daemon
    state: present
  tags: transmission

# Configuration
- name: Make sure transmission is not running
  service:
    name: transmission-daemon
    state: stopped
  ignore_errors: true
  tags: transmission

- name: Add downloads folder
  file:
    state: directory
    path: "{{ transmission_download_dir }}"
    owner: "{{ transmission_user }}"
    group: {{ transmission_user }}
    mode: 0775
  tags: transmission

- name: Add watch dir
  file:
    state: directory
    path: "{{ transmission_watch_dir }}"
    owner: "{{ transmission_user }}"
    group: {{ transmission_user }}
    mode: 0775
  when: transmission_watch_dir_enabled
  tags: transmission

- name: Add incomplete folder
  file:
    state: directory
    path: "{{ transmission_incomplete_dir }}"
    owner: "{{ transmission_user }}"
    group: {{ transmission_user }}
    mode: 0775
  when: transmission_incomplete_dir_enabled
  tags: transmission

- name: Create Transmission config directory
  file: path=/home/{{ transmission_user }}/.config/transmission-daemon state=directory mode=0755 owner={{ transmission_user }} group={{ transmission_user }}
  tags: transmission

- name: Copy Transmission configuration
  template:
    src: transmission-settings.json.j2
    dest: /home/{{ transmission_user }}/.config/transmission-daemon/settings.json
  tags: transmission

- name: Create Transmission info directory
  file: path=/home/{{ transmission_user }}/info state=directory mode=0755 owner={{ transmission_user }} group={{ transmission_user }}
  tags: transmission

- name: Create Transmission defaults file
  template: >
    src=../templates/transmission_default.j2
    dest=/home/{{ transmission_user }}/transmission_default
    owner={{ transmission_user }}
    group={{ transmission_user }}
    mode=0644
  tags: transmission

- name: Create Transmission symlink to defaults file
  file: >
    src=/home/{{ transmission_user }}/transmission_default
    dest=/etc/default/transmission-daemon
    force=yes
    state=link
  tags: transmission

- name: Create Transmission init directory
  file: path=/home/{{ transmission_user }}/init.d state=directory mode=0755 owner={{ transmission_user }}  
  tags: transmission

- name: Create Transmission init file link
  template: >
    src=../templates/transmission_init.j2
    dest=/home/{{ transmission_user }}/init.d/transmission-daemon
    owner={{ transmission_user }}
    group={{ transmission_user }}
    mode=0751
  tags: transmission

- name: Create Transmission symlink to init file link
  file: >
    src=/home/{{ transmission_user }}/init.d/transmission-daemon
    dest=/etc/init.d/transmission-daemon
    force=yes
    state=link
  tags: transmission

- name: Create Transmission upstart directory
  file: path=/home/{{ transmission_user }}/init state=directory mode=0755 owner={{ transmission_user }}  
  tags: transmission

- name: Create Transmission upstart file link
  template: >
    src=../templates/transmission_upstart.j2
    dest=/home/{{ transmission_user }}/init/transmission-daemon.conf
    owner={{ transmission_user }}
    group={{ transmission_user }}
    mode=0751
  tags: transmission

- name: Create Transmission symlink to upstart file link
  file: >
    src=/home/{{ transmission_user }}/init/transmission-daemon.conf
    dest=/etc/init/transmission-daemon.conf
    force=yes
    state=link
  tags: transmission

- name: Add current user to transmission group
  user:
    name: "{{ transmission_user }}"
    groups: {{ transmission_user }}
    append: yes
  tags: transmission

# Service start
- name: Start transmission
  service:
    name: transmission-daemon
    state: started
  ignore_errors: true
  tags: transmission